<?xml version='1.0' encoding='UTF-8'?>

<boundle>
	<msg name="notAcceptFile">
		<text lsid="CN">不允许上传文件。</text>
		<text lsid="EN">Upload file not accepted.</text>
	</msg>

	<msg name="exceedFileSizeLimit">
		<text lsid="CN">上传文件尺寸超过限制。</text>
		<text lsid="EN">Size of upload file exceed limit.</text>
	</msg>

	<msg name="exceedFileNumLimit">
		<text lsid="CN">上传文件个数超过限制。</text>
		<text lsid="EN">Number of upload file exceed limit.</text>
	</msg>

	<msg name="parseMultipartHeaderException">
		<text lsid="CN">分解MultipartHeader时遇到异常。</text>
		<text lsid="EN">Exception occur while parsing multipart header.</text>
	</msg>
</boundle>
