<?xml version='1.0' encoding='UTF-8'?>

<boundle>
	<msg name="type_0">
		<text lsid="CN">静态</text>
		<text lsid="EN">Static</text>
	</msg>

	<msg name="type_1">
		<text lsid="CN">动态</text>
		<text lsid="EN">Dynamic</text>
	</msg>

	<msg name="type_2">
		<text lsid="CN">组合</text>
		<text lsid="EN">Group</text>
	</msg>

	<msg name="type_3">
		<text lsid="CN">错误</text>
		<text lsid="EN">Error</text>
	</msg>
</boundle>
