<?xml version='1.0' encoding='UTF-8'?>

<boundle>
	<msg name="loadError(class, cfg, exp)">
		<text lsid="CN">为类(class)加载配置(cfg)遇到异常：(exp)</text>
		<text lsid="EN">Exception occur while load config "(cfg)" for class "(class)": (exp)</text>
	</msg>

	<msg name="notValidateConfig(class, cfg)">
		<text lsid="CN">为类(class)加载的配置(cfg)的类型不是ValidateConfig</text>
		<text lsid="EN">Object return by validate config loader for class "(class)", config name "(cfg)" is not of type "ValidateConfig"</text>
	</msg>
</boundle>
