<?xml version='1.0' encoding='UTF-8'?>

<boundle>
	<msg name="headStart">
		<text lsid="*"><![CDATA[<head>]]></text>
	</msg>

	<msg name="headEnd">
		<text lsid="*"><![CDATA[</head>]]></text>
	</msg>

	<msg name="style_app(url)">
		<text lsid="*"><![CDATA[<link rel="stylesheet" id="css" type="text/css" href="(url)" />]]></text>
	</msg>

	<msg name="script_app(url)">
		<text lsid="*"><![CDATA[<script language="javascript" src="(url)"></script>]]></text>
	</msg>

	<msg name="style_edit">
		<text lsid="*"><![CDATA[<link rel="stylesheet" id="css" type="text/css" href="/ap2/su/theme/edit.css" />]]></text>
	</msg>

	<msg name="script_edit">
		<text lsid="*"><![CDATA[<script language="javascript" src="/ap2/su/script/ctxmenu.js"></script>
<script language="javascript" src="/ap2/su/script/drag.js"></script>]]></text>
	</msg>

	<msg name="script_setPageID(pageID)">
		<text lsid="*"><![CDATA[<script language="javascript">window.siteup_pageID = "(pageID)";</script>]]></text>
	</msg>

	<msg name="style_html">
		<text lsid="*"><![CDATA[<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<link rel="stylesheet" id="css" type="text/css" href="/ap2/adk/html/styles/adk2012.css" />
<link rel="stylesheet" id="css" type="text/css" href="/ap2/adk/html/styles/ui_1.0.2.css" />
<link rel="stylesheet" id="css" type="text/css" href="/ap2/adk/html/jquery/jquery-ui-1.8.16.custom.css" />
<link rel="stylesheet" id="css" type="text/css" href="/ap2/adk/html/jquery/tools.tooltip.css" />]]></text>
	</msg>

	<msg name="style_html_apache">
		<text lsid="*"><![CDATA[<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<link rel="stylesheet" id="css" type="text/css" href="(0)/sys/adk/html/styles/adk2012.css" />
<link rel="stylesheet" id="css" type="text/css" href="(0)/sys/adk/html/styles/ui_1.0.2.css" />
<link rel="stylesheet" id="css" type="text/css" href="(0)/sys/adk/html/jquery/jquery-ui-1.8.16.custom.css" />
<link rel="stylesheet" id="css" type="text/css" href="(0)/sys/adk/html/jquery/tools.tooltip.css" />]]></text>
	</msg>

	<msg name="style_xhtml">
		<text lsid="*"><![CDATA[<link rel="stylesheet" id="css" type="text/css" href="/ap2/adk/xhtml/styles/adk2012.css" />]]></text>
	</msg>

	<msg name="style_xhtml_apache">
		<text lsid="*"><![CDATA[<link rel="stylesheet" id="css" type="text/css" href="(0)/sys/adk/xhtml/styles/adk2012.css" />]]></text>
	</msg>

	<msg name="script_html">
		<text lsid="*"><![CDATA[<script language="javascript" src="/ap2/adk/html/jquery/jquery-1.7.1.min.js"></script>
<script language="javascript" src="/ap2/ae/script/ae_ajax_jq_1.2.js"></script>
<script language="javascript" src="/ap2/adk/html/jquery/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="/ap2/adk/html/jquery/ui.datepicker-zh-CN.js"></script>
<script language="javascript" src="/ap2/adk/html/jquery/tools.tooltip-1.1.3.min.js"></script>
<script language="javascript" src="/ap2/adk/html/script/ibutils_1.2.js"></script>
<script language="javascript" src="/ap2/adk/html/script/ui_1.1.js"></script>]]></text>
	</msg>

	<msg name="script_html_apache">
		<text lsid="*"><![CDATA[<script language="javascript" src="(0)/sys/adk/html/jquery/jquery-1.7.1.min.js"></script>
<script language="javascript" src="(0)/sys/ae/script/ae_ajax_jq_1.2.js"></script>
<script language="javascript" src="(0)/sys/adk/html/jquery/jquery-ui-1.8.16.custom.min.js"></script>
<script language="javascript" src="(0)/sys/adk/html/jquery/ui.datepicker-zh-CN.js"></script>
<script language="javascript" src="(0)/sys/adk/html/jquery/tools.tooltip-1.1.3.min.js"></script>
<script language="javascript" src="(0)/sys/adk/html/script/ibutils_1.2.js"></script>
<script language="javascript" src="(0)/sys/adk/html/script/ui_1.1.js"></script>]]></text>
	</msg>

	<msg name="script_html_static">
		<text lsid="*"><![CDATA[<script language="javascript" src="(0)/sys/ae/script/ae_static_1.0.js"></script>]]></text>
	</msg>
</boundle>