<?xml version='1.0' encoding='UTF-8'?>

<boundle>
	<msg name="noEndBracket(name)">
		<text lsid="CN">文本信息名称中缺少右括号：“(name)”。</text>
		<text lsid="EN">No ending bracket in message name: "(name)".</text>
	</msg>

	<msg name="endBracketNotAtEnd(name)">
		<text lsid="CN">右括号不在最后：“(name)”。</text>
		<text lsid="EN">Ending bracket is not at the end: "(name)".</text>
	</msg>

	<msg name="noParameter(name)">
		<text lsid="CN">括号内没有参数：“(name)”。</text>
		<text lsid="EN">No parameter in brackets: "(name)".</text>
	</msg>

	<msg name="parameterError(name)">
		<text lsid="CN">参数格式错误：“(name)”。</text>
		<text lsid="EN">Parameter format error: "(name)".</text>
	</msg>

	<msg name="parameterNotReferenced(text, param)">
		<text lsid="CN">文本信息“(text)”中没有引用参数“(param)”。</text>
		<text lsid="EN">Parameter "(param)" not referenced in text "(text)".</text>
	</msg>
</boundle>
